name: Build and Package Electron App

on:
  push:
    branches:
      - main # Change this to the branch you want to build from

jobs:
  build_and_package:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to the latest version

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Updated to the latest version
        with:
          node-version: "18" # Change this to your preferred Node.js version

      # Cache npm dependencies
      - name: Cache npm dependencies
        uses: actions/cache@v3 # Updated to the latest version
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Cache TypeScript output
      - name: Cache TypeScript build
        uses: actions/cache@v3 # Updated to the latest version
        with:
          path: ./dist
          key: ${{ runner.os }}-tsc-${{ hashFiles('**/tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-tsc-

      # Install dependencies
      - name: Install dependencies
        run: npm install

        # Install snapcraft on Linux
      - name: Install snapcraft on Linux
        run: sudo snap install snapcraft --classic
        if: runner.os == 'Linux'

      # Install multipass on Linux
      - name: Install multipass on Linux
        run: sudo snap install multipass --classic
        if: runner.os == 'Linux'

        # Build the app
      - name: Build app
        run: npm run build # This should run tsc and vite build

      # Set version as env
      - name: Set version as env
        run: echo "APP_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-app
          path: |
            ./release/${{ env.APP_VERSION }}/**/*.exe
            ./release/${{ env.APP_VERSION }}/**/*.AppImage
            ./release/${{ env.APP_VERSION }}/**/*.dmg
