name: Build and Package Electron App

on:
  push:
    branches:
      - main

jobs:
  build_and_package:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Cache TypeScript build
        uses: actions/cache@v3
        with:
          path: ./dist
          key: ${{ runner.os }}-tsc-${{ hashFiles('**/tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-tsc-

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      # Specific step for Linux builds
      - name: Run Linux Specific Command
        if: matrix.os == 'ubuntu-latest'
        run: npx --no node-llama-cpp download

      - name: Set version as env
        run: echo "APP_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-app
          path: |
            ./release/${{ env.APP_VERSION }}/**/*.exe
            ./release/${{ env.APP_VERSION }}/**/*.AppImage
            ./release/${{ env.APP_VERSION }}/**/*.dmg
