name: Build and Package Electron App

on:
  push:
    branches:
      - main # Change this to the branch you want to build from

jobs:
  build_and_package:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to the latest version

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Updated to the latest version
        with:
          node-version: "18" # Change this to your preferred Node.js version

      # Cache npm dependencies
      - name: Cache npm dependencies
        uses: actions/cache@v3 # Updated to the latest version
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Cache TypeScript output
      - name: Cache TypeScript build
        uses: actions/cache@v3 # Updated to the latest version
        with:
          path: ./dist
          key: ${{ runner.os }}-tsc-${{ hashFiles('**/tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-tsc-

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the app
      - name: Build app
        run: npm run build # This should run tsc and vite build

      # Package the app for different operating systems
      - name: Package App
        run: |
          if ($env:RUNNER_OS -eq "Windows") {
          npm run package-win
          } elseif ($env:RUNNER_OS -eq "Linux") {
          npm run package-linux
          } elseif ($env:RUNNER_OS -eq "macOS") {
          npm run package-mac
          }
        shell: pwsh
        env:
          RUNNER_OS: ${{ runner.os }}
      - name: Set version as env
        run: echo "APP_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-app
          path: |
            ./release/${{ matrix.os }}/${{ env.APP_VERSION }}/**/*.exe
            ./release/${{ matrix.os }}/${{ env.APP_VERSION }}/**/*.AppImage
            ./release/${{ matrix.os }}/${{ env.APP_VERSION }}/**/*.dmg
